### ISSUE TITLE
can isotp error handler

### ISSUE THREAD

**Issue by SeifHadrich** [hartkopp/can-isotp-modules#5]
I am wondering how we could check if an error  has been occurred while sending or receiving a isotp message ?
I wasn't able to find any doc about the error handler.
Thanks

**Comment by hartkopp** [comment]
As usual when interacting with network socket you get a return value which either tells you how many bytes were written or whether an error occurred.

There have been different improvement in the Linux kernel implementation (in Mainline Kernel since 5.10), that could to be backported to the out of tree implementation, which can be found here: https://github.com/hartkopp/can-isotp 

THIS REPOSITORY IS OBSOLETE SINCE 2017 - therefore closing this issue here.
If you still have questions please open a new issue there.

Thanks
